### ISSUE TITLE
Unreachable zip file in github action

### ISSUE THREAD

**Issue by alainib** [expo/vector-icons#328]
hello 

my github action fail because of this error

how to solve this please ?

```
YN0001: Error: While persisting /Users/runner/.yarn/berry/cache/@expo-vector-icons-npm-14.1.0-9ab4f0997d-10c0.zip/node_modules/@expo/vector-icons/ -> /Users/runner/work/gift-cool/cool/node_modules/@expo/vector-icons Unreachable
    at Zi.statImpl (/Users/runner/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:149:202677)
    at /Users/runner/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:149:215318
    at Function.from (<anonymous>)
    at Zi.readdirSync 
```

if fail on yarn install last step, it was working just yesterday and i didn't touch anythink here :( 

```
name: iOS Build PP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-15
    environment: testing
    steps:
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Update CocoaPods version
        run: |
          gem install cocoapods
      - name: Print CocoaPods version
        run: |
          pod --version
      - name: Check out Git repository
        uses: actions/checkout@v4.2.1

      - name: Set Node.js version
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 23.0.0

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4.5.1
        run: corepack prepare yarn@4.5.1 --activate

      - name: Print Yarn Config immutable flag value
        run: yarn config get enableImmutableInstalls

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.development
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

     #  same error with or without yarn-cache
      - name: Cache node_modules and yarn cache
        uses: actions/cache@v4.2.0
        id: yarn-cache
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Remove node_modules
        run: rm -rf node_modules

     # i tried to clean cache folder
      - name: Clean Yarn Berry cache
        run: rm -rf .yarn/cache/*

      - name: Clear Yarn cache
        run: yarn cache clean --all

      - name: Install dependencies  
        run: yarn install  
 ```
